---
- name: Configure Redis
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    create: true
    owner: root
    group: root
    mode: "0644"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ redis_settings }}"
  notify: Restart redis
