---
- name: Add nginx logrotate config
  ansible.builtin.copy:
    src: nginx-logrotate
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: "0644"
    validate: 'logrotate -d %s'
