---
- name: Copy gzip config file
  ansible.builtin.copy:
    src: gzip.conf
    dest: /etc/nginx/conf.d/
    owner: root
    mode: '0644'
  notify: Restart nginx

- name: Copy website config file
  ansible.builtin.copy:
    src: amedee.be
    dest: /etc/nginx/sites-available/
    owner: root
    mode: '0644'
  notify: Restart nginx

- name: Delete DigitalOcean website config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/digitalocean
    state: absent
  notify: Restart nginx

- name: Create a symbolic link
  ansible.builtin.file:
    src: /etc/nginx/sites-available/amedee.be
    dest: /etc/nginx/sites-enabled/default
    owner: root
    state: link
  notify: Restart nginx

- name: "Check existence of webserver directory {{ webserver_directory }}"
  ansible.builtin.file:
    path: "{{ webserver_directory }}"
    state: directory
    owner: "{{ webserver_user }}"
    group: "{{ webserver_user }}"
    mode: u=rwx,go=rx
