---
- name: Configure APT repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types:
      - deb
    uris:
      - "{{ item.uri }}"
    suites:
      - "{{ nginx_apt_suite }}"
    components:
      - "{{ item.component }}"
    signed_by: "{{ item.key }}"
  loop: "{{ nginx_repositories }}"

- name: Configure APT pinning
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/apt/preferences.d/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ nginx_apt_pinning_files }}"

- name: Install Nginx and PHP
  ansible.builtin.apt:
    name:
      - nginx
      - php
      - php-fpm
    update_cache: true
    cache_valid_time: 86400 # One day
    lock_timeout: 300 # 5 minutes

- name: Deploy nginx configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ nginx_config_files }}"
  notify: Reload nginx

- name: Copy website config file
  ansible.builtin.template:
    src: website.j2
    dest: /etc/nginx/sites-available/{{ nginx_hostname }}
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Delete DigitalOcean website config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/digitalocean
    state: absent
  notify: Reload nginx

- name: Enable website
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ nginx_hostname }}
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Reload nginx

- name: Validate nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  register: nginx_test

- name: "Check existence of webserver directory {{ nginx_directory }}"
  ansible.builtin.file:
    path: "{{ nginx_directory }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0755"

- name: Configure logrotate for nginx logs
  ansible.builtin.import_tasks: logrotate.yml
