---
mailserver_packages:
  - postfix
  - postfix-pcre

mailserver_postfix_directories:
  - /etc/postfix/checks
  - /etc/postfix/sasl

mailserver_postfix_settings:
  - { regexp: '^body_checks', line: 'body_checks = pcre:/etc/postfix/checks/body_checks.pcre'}
  - { regexp: '^header_checks', line: 'header_checks = pcre:/etc/postfix/checks/header_checks.pcre'}
  - { regexp: '^header_size_limit', line: 'header_size_limit = 4096000' }
  - { regexp: '^mime_header_checks', line: 'mime_header_checks = pcre:/etc/postfix/checks/mime_header_checks.pcre'}
  - { regexp: '^recipient_delimiter', line: 'recipient_delimiter = -' }
  - { regexp: '^relayhost', line: 'relayhost = [smtp.sendgrid.net]:587' }
  - { regexp: '^smtp_sasl_auth_enable', line: 'smtp_sasl_auth_enable = yes' }
  - { regexp: '^smtp_sasl_password_maps', line: 'smtp_sasl_password_maps = hash:/etc/postfix/sasl/sasl_passwd' } # pragma: allowlist-secret
  - { regexp: '^smtp_sasl_security_options', line: 'smtp_sasl_security_options = noanonymous' }
  - { regexp: '^smtp_sasl_tls_security_options', line: 'smtp_sasl_tls_security_options = noanonymous' }
  - { regexp: '^smtp_tls_security_level', line: 'smtp_tls_security_level = encrypt' }
