---
dependencies:
  - role: geerlingguy.swap
    swap_file_size_mb: '4096'
  - role: debops.debops.unattended_upgrades
  - role: debops.debops.cron
    cron__jobs:
      hadori:
        name: 'Hardlink with hadori'
        special_time: 'monthly'
        job: '/usr/bin/hadori --verbose /bin /sbin /lib /lib64 /usr /opt'
