---
# @meta author:value: [Amedee Van Gasse](https://amedee.be)
galaxy_info:
  description: Role to configure install and configure common stuff on all of my servers.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies:
  - role: geerlingguy.munin-node
    munin_node_allowed_ips:
      - ^127\.0\.0\.1$
      - "^::1$"
      - ^142\.93\.227\.16$
    munin_node_config:
      "df*":
        env.warning: 92
        env.critical: 98
        env.exclude: >-
          none unknown rootfs iso9660 squashfs udf romfs ramfs debugfs
          cgroup_root devtmpfs nilfs2 tmpfs
        env.exclude_re: ^/dev/shm ^/run
      df:
        env.include_re: ^/boot/efi$
      df_inode:
        env.exclude_re: ^/boot/efi$
      "diskstats*":
        env.include_only: vd
