---
- name: Validate Postfix configuration
  ansible.builtin.command:
    cmd: postfix check
  changed_when: false

- name: Restart Postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: not postfix_ses_molecule | default(false)
