---
galaxy_info:
  author: Amedee Van Gasse
  description: Merges two dicts into a third one using combine()
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
