---
name: ♻️ Restore Ansible Cache
description: Restores and relocates Ansible role/collection cache

runs:
  using: "composite"
  steps:
    - name: Restore Ansible roles and collections cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          /home/runner/.ansible/collections
          /home/runner/.ansible/roles
        key: ansible-deps-${{ hashFiles('requirements.yml') }}

    - name: Install Galaxy roles
      shell: bash
      run: |
        ansible-galaxy role install \
          -r requirements.yml \
          -p /home/runner/.ansible/roles

    - name: Install Galaxy collections
      shell: bash
      run: |
        ansible-galaxy collection install \
          -r requirements.yml \
          -p /home/runner/.ansible/collections
