---
name: ♻️ Restore Ansible Cache
description: Restores and relocates Ansible role/collection cache

runs:
  using: "composite"
  steps:
    - name: Restore Ansible roles and collections cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          /home/runner/.ansible/collections
          roles
        key: ansible-deps-${{ hashFiles('requirements.yml') }}

    - name: Install Galaxy dependencies (with retry)
      shell: bash
      run: ansible-galaxy install -r requirements.yml
