---
- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart redis
  become: true
  ansible.builtin.service:
    name: redis-server
    state: restarted
