---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify MySQL server is installed
      ansible.builtin.assert:
        that:
          - "'mysql-server' in ansible_facts.packages"
        fail_msg: MySQL server package is not installed.

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Verify MySQL service is running
      ansible.builtin.assert:
        that:
          - "'mysql.service' in ansible_facts.services"
          - ansible_facts.services['mysql.service'].state == 'running'
        fail_msg: MySQL service is not running.

    - name: Get MySQL root authentication plugin
      ansible.mysql.mysql_query:
        query: >
          SELECT plugin
          FROM mysql.user
          WHERE User = 'root'
            AND Host = 'localhost';
        login_user: root
        login_unix_socket: /run/mysqld/mysqld.sock
      register: mysql_root_plugin
      changed_when: false

    - name: Verify MySQL root uses auth_socket
      ansible.builtin.assert:
        that:
          - mysql_root_plugin.query_result[0][0].plugin == 'auth_socket'
