---
name: Format Markdown with Prettier
description: Format Markdown files with Prettier

runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24

    - name: Format Markdown
      shell: bash
      run: |
        npx --yes prettier \
          --prose-wrap always \
          --print-width 80 \
          --write "**/*.md"
