---
root: true

env:
  node: true
  es2022: true

parserOptions:
  ecmaVersion: 2022
  sourceType: module

extends:
  - eslint:recommended

rules:
  no-undef: error
  no-unused-vars:
    - warn
    - argsIgnorePattern: "^_"
  no-prototype-builtins: "off"
  no-var: error
  prefer-const: warn
  require-yield: "off"
