---
roles:
  - name: geerlingguy.munin-node
    version: 1.4.0

collections:
  - name: amazon.aws
    version: 10.1.1
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: community.docker
    version: 4.7.0
  - name: community.general
    version: 11.3.0
  - name: community.mysql
    version: 3.16.0
  - name: debops.debops
    version: 3.2.4
