---
roles:
  - name: geerlingguy.munin-node
    version: 1.4.0
  - name: rolehippie.swap
    version: v2.0.0

collections:
  - name: amazon.aws
    version: 9.1.1
  - name: ansible.posix
    version: 2.0.0
  - name: community.general
    version: 10.4.0
  - name: community.mysql
    version: 3.12.0
  - name: debops.debops
    version: 3.2.4
