---
roles:
  - name: geerlingguy.swap
    version: 1.2.0

collections:
  - name: amazon.aws
    version: 8.1.0
  - name: community.general
    version: 9.2.0
  - name: community.mysql
    version: 3.9.0
