---
roles:
  - name: geerlingguy.munin-node
    version: 1.4.0

collections:
  - name: amazon.aws
    version: 11.1.0
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: community.docker
    version: 5.0.6
  - name: community.general
    version: 12.3.0
  - name: community.mysql
    version: 4.1.0
  - name: debops.debops
    version: 3.2.5
