---
- name: Ensure software is installed
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    pkg: "{{ mailserver_packages }}"

- name: Create directories if they don't exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: u=rwx,go=rx
  loop: "{{ mailserver_postfix_directories }}"

- name: Load Sendgrid API key
  ansible.builtin.include_vars:
    file: sendgrid.yml
    name: sendgrid

- name: Create /etc/postfix/sasl/sasl_passwd from template
  become: true
  ansible.builtin.template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl/sasl_passwd
    owner: root
    mode: u=rw,go=
  notify:
    - Update Postfix hashtables

- name: Copy checks files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/postfix/checks/
    owner: root
    mode: u=rw,go=r
  with_fileglob: "checks/*_checks.pcre"
  notify: Restart Postfix

- name: Configure Postfix
  become: true
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    create: true
    owner: root
    mode: u=rw,go=r
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ mailserver_postfix_settings }}"
  notify: Restart Postfix

- name: Configure logrotate for Postfix
  become: true
  ansible.builtin.copy:
    src: postfix
    dest: /etc/logrotate.d/postfix
    owner: root
    mode: u=rw,go=r
  notify: Restart Rsyslog
