---
- name: Install APT packages
  ansible.builtin.apt:
    state: present
    pkg: "{{ mailserver_apt_packages }}"

- name: Copy Postfix checks files
  ansible.builtin.copy:
    src: etc/postfix/checks/
    dest: /etc/postfix/checks/
    owner: root
    mode: u=rw,go=r
    directory_mode: u=rwx,go=rx
  notify:
    - Restart Postfix

- name: Create directory /etc/postfix/sasl/
  ansible.builtin.file:
    path: /etc/postfix/sasl/
    state: directory
    owner: root
    mode: u=rwx,go=rx

- name: Create /etc/postfix/sasl/sasl_passwd from template
  ansible.builtin.template:
    src: etc/postfix/sasl/sasl_passwd.j2
    dest: /etc/postfix/sasl/sasl_passwd
    owner: root
    mode: u=rw,go=
  notify: Update Postfix hashtables

- name: Configure Postfix
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    create: true
    owner: root
    mode: u=rw,go=r
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ mailserver_postfix_settings }}"
  notify: Restart Postfix
