---
- name: Ensure Postfix is installed
  ansible.builtin.apt:
    name: postfix
    state: present
  tags:
    - install

- name: Create directories if they don't exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: u=rwx,go=rx
  loop: "{{ mailserver_postfix_directories }}"
  tags:
    - config

- name: Load Sendgrid API key
  ansible.builtin.include_vars:
    file: sendgrid.yml
    name: sendgrid
  tags:
    - config

- name: Create /etc/postfix/sasl/sasl_passwd from template
  ansible.builtin.template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl/sasl_passwd
    owner: root
    mode: u=rw,go=
  notify:
    - Update Postfix hashtables
    - Restart Postfix
  tags:
    - config

- name: Copy checks files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/postfix/checks/
    owner: root
    mode: u=rw,go=r
  with_fileglob: "checks/*_checks.pcre"
  notify: Restart Postfix
  tags:
    - config

- name: Configure Postfix
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    create: true
    owner: root
    mode: u=rw,go=r
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ mailserver_postfix_settings }}"
  notify: Restart Postfix
  tags:
    - config
