---
- name: Configure Ubuntu package repositories
  ansible.builtin.deb822_repository:
    name: ubuntu
    types:
      - deb
    uris:
      - http://mirrors.digitalocean.com/ubuntu/
    suites:
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_release }}-updates"
      - "{{ ansible_distribution_release }}-backports"
    components:
      - main
      - restricted
      - universe
      - multiverse
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg

- name: Configure Ubuntu security repository
  ansible.builtin.deb822_repository:
    name: ubuntu-security
    types:
      - deb
    uris:
      - http://security.ubuntu.com/ubuntu
    suites:
      - "{{ ansible_distribution_release }}-security"
    components:
      - main
      - restricted
      - universe
      - multiverse
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg

- name: Disable APT Phasing
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99disable-phasing
    content: 'APT::Get::Always-Include-Phased-Updates "true";'
    owner: root
    group: root
    mode: "0644"

- name: Remove unwanted packages
  ansible.builtin.apt:
    state: absent
    pkg: "{{ apt_packages_uninstall }}"
  notify:
    - APT autoclean
    - APT autoremove
