---
name: Create or Update PR
description: Commit changes, push to a branch, and create or update a pull request.

inputs:
  branch:
    description: "Branch to push changes to"
    required: true
  commit_message:
    description: "Full commit message"
    required: true
  pr_title:
    description: "Title for the pull request"
    required: true
  pr_body:
    description: "Body for the pull request"
    required: true
  github_token:
    description: "GitHub token with write access"
    required: true
  git_user_name:
    description: "Git user.name to use for commits"
    required: true
  git_user_email:
    description: "Git user.email to use for commits"
    required: true

outputs:
  pushed:
    description: "Whether changes were pushed"
    value: ${{ steps.commit_push.outputs.pushed }}

runs:
  using: composite
  steps:
    - shell: bash
      id: commit_push
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        INPUTS_GIT_USER_NAME: ${{ inputs.git_user_name }}
        INPUTS_GIT_USER_EMAIL: ${{ inputs.git_user_email }}
        INPUTS_BRANCH: ${{ inputs.branch }}
        INPUTS_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        INPUTS_GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -e

        git config user.name "${INPUTS_GIT_USER_NAME}"
        git config user.email "${INPUTS_GIT_USER_EMAIL}"
        git checkout -B "${INPUTS_BRANCH}"
        git add .

        if git diff --cached --quiet; then
          echo "🟡 No staged changes to commit."
          echo "pushed=false" >> "$GITHUB_OUTPUT"
        else
          echo "✅ Committing changes..."
          git commit -m "${INPUTS_COMMIT_MESSAGE}"
          REPO_URL="https://x-access-token:${INPUTS_GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push --force "$REPO_URL" "${INPUTS_BRANCH}"
          echo "pushed=true" >> "$GITHUB_OUTPUT"
        fi

    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        INPUTS_BRANCH: ${{ inputs.branch }}
        INPUTS_PR_TITLE: ${{ inputs.pr_title }}
        INPUTS_PR_BODY: ${{ inputs.pr_body }}
      run: |
        set -e

        REPO="${GITHUB_REPOSITORY}"
        BRANCH="${INPUTS_BRANCH}"

        echo "🔍 Checking if PR exists from branch '$BRANCH'..."
        PR_JSON=$(gh pr list \
          --repo "$REPO" \
          --head "$BRANCH" \
          --json number \
          --jq '.[0]')

        if [[ -n "$PR_JSON" ]]; then
          PR_NUMBER=$(echo "$PR_JSON" | jq -r .number)
          echo "🔄 PR #$PR_NUMBER exists, updating..."
          gh pr edit "$PR_NUMBER" \
            --repo "$REPO" \
            --title "${INPUTS_PR_TITLE}" \
            --body "${INPUTS_PR_BODY}"
        else
          echo "🆕 No PR found, creating a new one..."
          gh pr create \
            --repo "$REPO" \
            --base main \
            --head "$BRANCH" \
            --title "${INPUTS_PR_TITLE}" \
            --body "${INPUTS_PR_BODY}"
        fi
