---
nginx_apt_suite: "{{ ansible_distribution_release }}"
nginx_default_indexfiles:
  - index.php
  - index.html
nginx_directory: "{{ webserver_directory | default('/var/www/html') }}"
nginx_hostname: "{{ hostname | default('localhost') }}"
nginx_php_version: "{{ php_version | default('8.4') }}"
nginx_user: "{{ webserver_user | default('www-data') }}"

nginx_repositories:
  - name: nginx
    uri: https://nginx.org/packages/ubuntu
    component: nginx
    key: https://nginx.org/keys/nginx_signing.key

  - name: sury-php
    uri: https://packages.sury.org/php/
    component: main
    key: https://packages.sury.org/php/apt.gpg

nginx_apt_pinning_files:
  - pin_nginx.pref
  - pin_php.pref

nginx_config_files:
  - src: nginx.conf
    dest: /etc/nginx/nginx.conf
  - src: gzip.conf
    dest: /etc/nginx/conf.d/gzip.conf
