---
- name: DNS update
  ansible.builtin.include_tasks: tasks/dns_update.yml

- name: Restart munin
  ansible.builtin.service:
    name: munin
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  notify: Restart munin-node

- name: Restart munin-node
  ansible.builtin.service:
    name: munin-node
    state: restarted

- name: Perform backup
  ansible.builtin.command:
    cmd: /root/mailinabox/management/backup.py
  changed_when: true
