---
- name: Copy Postfix checks files
  ansible.builtin.copy:
    src: etc/postfix/checks/
    dest: /etc/postfix/checks/
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Postfix

- name: Generate Postfix recipient access map
  ansible.builtin.template:
    src: postfix_invalid_recipients.j2
    dest: /etc/postfix/checks/invalid_recipients.pcre
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Postfix

- name: Ensure recipient canonical PCRE map exists
  ansible.builtin.copy:
    dest: /etc/postfix/recipient-canonical-maps.pcre
    content: |
      /^(.*)-[^@]+@(.*)$/     ${1}@$2
    owner: root
    group: root
    mode: '0644'
  notify: Restart Postfix

- name: Build dynamic Postfix settings
  ansible.builtin.set_fact:
    postfix_dynamic_settings:
      myhostname: "{{ ansible_hostname }}"
      mydestination: >-
        {{
          (['$myhostname', ansible_hostname, 'localhost.localdomain', 'localhost'] +
           mydomains
          ) | unique | join(', ')
        }}

- name: Merge static and dynamic Postfix settings
  ansible.builtin.set_fact:
    postfix_settings: "{{ postfix_dynamic_settings | combine(postfix_static_settings) }}"

- name: Get current Postfix settings
  ansible.builtin.command: postconf -n
  register: current_postfix_output
  changed_when: false

- name: Parse current Postfix settings into a dict
  ansible.builtin.set_fact:
    current_postfix_settings: >-
      {{
        dict(
          current_postfix_output.stdout_lines
          | map('split', ' =', 1)
          | map('map', 'trim')
        )
      }}

- name: Apply Postfix settings - set or delete
  ansible.builtin.command: >
    {% if item.value is none %}
      postconf -X {{ item.key }}
    {% else %}
      postconf -e {{ (item.key ~ ' = ' ~ (item.value | string)) | quote }}
    {% endif %}
  loop: "{{ postfix_settings | dict2items }}"
  when: >
    (item.value is none and item.key in current_postfix_settings)
    or
    (item.value is not none and
     (item.key not in current_postfix_settings or
      current_postfix_settings[item.key] != (item.value | string)))
  changed_when: true
  check_mode: false
  notify: Restart Postfix

- name: Read current smtpd_recipient_restrictions from Postfix
  ansible.builtin.command: postconf -h smtpd_recipient_restrictions
  register: smtpd_restrictions
  changed_when: false
  failed_when: false
  check_mode: false

- name: Define the check_line value
  ansible.builtin.set_fact:
    check_line: "check_recipient_access pcre:/etc/postfix/checks/invalid_recipients.pcre"

- name: Parse current smtpd_recipient_restrictions into list
  ansible.builtin.set_fact:
    old_list: "{{ smtpd_restrictions.stdout.split(',') | map('trim') | list }}"
  when:
    - smtpd_restrictions.stdout is defined

- name: Prepare new smtpd_recipient_restrictions list
  ansible.builtin.set_fact:
    new_list: >-
      {%- if 'permit_mynetworks' in old_list -%}
      {{
        old_list[: old_list.index('permit_mynetworks') + 1]
        + [check_line]
        + old_list[old_list.index('permit_mynetworks') + 1 :]
      }}
      {%- else -%}
      {{ old_list + [check_line] }}
      {%- endif -%}
  when:
    - not ansible_check_mode
    - old_list is defined
    - smtpd_restrictions.stdout is defined
    - smtpd_restrictions.stdout | length > 0
    - check_line not in smtpd_restrictions.stdout

- name: Update smtpd_recipient_restrictions using postconf
  ansible.builtin.command: >
    postconf -e smtpd_recipient_restrictions="{{ new_list | join(', ') }}"
  when:
    - not ansible_check_mode
    - new_list is defined
    - smtpd_restrictions.stdout is defined
    - smtpd_restrictions.stdout | length > 0
    - check_line not in smtpd_restrictions.stdout
  changed_when: true
  notify: Restart Postfix

- name: Configure SendGrid Web API
  ansible.builtin.import_tasks: sendgrid.yml
