---
- name: Install Postfix dependencies
  ansible.builtin.apt:
    name:
      - logrotate
      - mailutils
      - postfix
      - postfix-pcre
      - procmail
      - swaks
    state: present

- name: Ensure /etc/postfix/checks/ directory exists
  ansible.builtin.file:
    path: /etc/postfix/checks/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy Postfix checks files
  ansible.builtin.copy:
    src: checks/
    dest: /etc/postfix/checks/
    owner: root
    group: root
    mode: "0644"

- name: Generate Postfix recipient access map
  ansible.builtin.template:
    src: postfix_invalid_recipients.j2
    dest: /etc/postfix/checks/invalid_recipients.pcre
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart Postfix

- name: Ensure sender canonical PCRE map exists
  ansible.builtin.copy:
    dest: /etc/postfix/sender-canonical-maps.pcre
    content: |
      /^.+$/    amedee@vangasse.eu
    owner: root
    group: root
    mode: "0644"
  notify: Restart Postfix

- name: Ensure recipient canonical PCRE map exists
  ansible.builtin.copy:
    dest: /etc/postfix/recipient-canonical-maps.pcre
    content: |
      /^(.*)-[^@]+@(.*)$/     ${1}@$2
    owner: root
    group: root
    mode: "0644"
  notify: Restart Postfix

- name: Configure Postfix main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Postfix

- name: Configure Postfix master.cf
  ansible.builtin.template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Postfix

- name: Configure logrotate for postfix logs
  ansible.builtin.import_tasks: logrotate.yml
