---
dependencies:
  - role: common
  - role: debops.debops.apt_preferences
    apt_preferences__list:
      - package: 'php'
        version: '*rc'
        priority: '-1'
        reason: |-
          I don't want a RC version of PHP
  - role: boto
