---
galaxy_info:
  description: Role to configure my webserver.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies:
  - role: common
  - role: debops.debops.apt_preferences
    apt_preferences__list:
      - package: php
        version: "*rc"
        priority: -1
        reason: |-
          I don't want a RC version of PHP
  - role: boto
