---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx

  roles:
    - role: letsencrypt
      letsencrypt_restore_from_backup: false
