---
webserver_packages:
  - curl
  - ghostscript
  - imagemagick
  - mysql-client
  - nginx
  - openssl
  - php
  - php-curl
  - php-imagick
  - php-intl
  - php-json
  - php-mbstring
  - php-mysql
  - php-ssh2
  - php-xml
  - php-xmlrpc
  - php-zip

webserver_wpcli_path: /usr/local/bin/wp
webserver_wpcli_url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
webserver_directory: /var/www/html
webserver_default_indexfiles:
  - index.html
  - index.nginx-debian.html
