---
webserver_apt_packages:
  - curl
  - elinks
  - ghostscript
  - imagemagick
  - mysql-client
  - nginx
  - openssl
  - php
  - php-curl
  - php-fpm
  - php-imagick
  - php-intl
  - php-json
  - php-mbstring
  - php-mysql
  - php-ssh2
  - php-xml
  - php-xmlrpc
  - php-zip

webserver_directory: /var/www/html
webserver_default_indexfiles:
  - index.html
  - index.nginx-debian.html
webserver_user: www-data
