---
webserver_packages:
  - curl
  - ghostscript
  - imagemagick
  - mysql-client
  - nginx
  - openssl
  - php
  - php-curl
  - php-imagick
  - php-intl
  - php-json
  - php-mbstring
  - php-mysql
  - php-ssh2
  - php-xml
  - php-xmlrpc
  - php-zip
