#!/bin/bash

/var/log/mail.log
/var/log/mail.err
{
    monthly
    rotate 24
    missingok
    notifempty
    compress
    delaycompress
    extension log
    create 0644 root root
    sharedscripts
    postrotate
        systemctl restart rsyslog
        systemctl restart postfix
    endscript
}
