---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: Read APT phasing configuration
      ansible.builtin.slurp:
        path: /etc/apt/apt.conf.d/99disable-phasing
      register: apt_phasing_content

    - name: Assert APT phasing configuration content
      ansible.builtin.assert:
        that:
          - >
            (apt_phasing_content.content | b64decode | trim)
            == 'APT::Get::Always-Include-Phased-Updates "true";'

    - name: Validate APT sources are usable # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: apt-get update
      changed_when: false
