---
- name: APT autoclean
  ansible.builtin.apt:
    autoclean: true

- name: APT autoremove
  ansible.builtin.apt:
    autoremove: true

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: install_software_reboot
  changed_when: true
  notify: Reboot

- name: Reboot
  when: install_software_reboot.stat.exists
  ansible.builtin.reboot:
    reboot_timeout: 3600
