---
# @meta author:value: [Amedee Van Gasse](https://amedee.be)
galaxy_info:
  description: Role to configure my WordPress blog.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies:
  - role: mailserver
  - role: dbserver
  - role: webserver
  - role: boto
  - role: debops.debops.keyring
    keyring__dependent_gpg_keys:
      - id: 63AF7AA15067C05616FDDD88A3A2E8F226F0BC06
  - role: debops.debops.wpcli
