---
dependencies:
  - role: mailserver
  - role: dbserver
  - role: webserver
  - role: boto
  - role: debops.debops.keyring
    keyring__dependent_gpg_keys:
      - id: 63AF7AA15067C05616FDDD88A3A2E8F226F0BC06
  - role: debops.debops.wpcli
