---
- name: Configure DigitalOcean Ubuntu mirror
  ansible.builtin.deb822_repository:
    name: ubuntu
    types:
      - deb
    uris:
      - http://mirrors.digitalocean.com/ubuntu/
    suites:
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_release }}-updates"
      - "{{ ansible_distribution_release }}-backports"
    components:
      - main
      - restricted
      - universe
      - multiverse
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg

- name: Configure Ubuntu security repository
  ansible.builtin.deb822_repository:
    name: ubuntu-security
    types:
      - deb
    uris:
      - http://security.ubuntu.com/ubuntu
    suites:
      - "{{ ansible_distribution_release }}-security"
    components:
      - main
      - restricted
      - universe
      - multiverse
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg

- name: Remove unwanted packages
  ansible.builtin.apt:
    state: absent
    pkg: "{{ apt_packages_uninstall }}"
  notify:
    - APT autoclean
    - APT autoremove
