---
- name: Install APT preferences
  ansible.builtin.copy:
    src: preferences.d/
    dest: /etc/apt/preferences.d/
    owner: root
    group: root
    mode: "0644"

- name: Configure deb822-format APT repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: "{{ item.repo.types | default(omit) }}"
    uris: "{{ item.repo.uris }}"
    suites: "{{ item.repo.suites }}"
    components: "{{ item.repo.components }}"
    signed_by: "{{ item.repo.signed_by }}"
    state: present
  loop: "{{ deb822_repositories }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400 # One day
    lock_timeout: 300 # 5 minutes

- name: Remove unwanted packages
  ansible.builtin.apt:
    state: absent
    pkg: "{{ apt_packages_uninstall }}"
  notify:
    - APT autoclean
    - APT autoremove
