---
name: Setup Python and Install Dependencies
description: Setup Python, cache pip packages, and install dependencies from a requirements file

inputs:
  python-version:
    description: "Python version to use"
    default: "3.x"
  requirements-file:
    description: "Path to the requirements file"
    default: "requirements.txt"

runs:
  using: "composite"
  steps:
    - name: 🛠️ Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: ${{ inputs.requirements-file }}

    - name: 📦 Install dependencies from requirements file
      run: |
        python -m pip install --upgrade pip
        pip install -r "${INPUTS_REQUIREMENTS_FILE}"
      shell: bash

      env:
        INPUTS_REQUIREMENTS_FILE: ${{ inputs.requirements-file }}
