---
name: Setup Python and Install Dependencies
description: Setup Python, cache pip packages, and install dependencies from a requirements file

inputs:
  python-version:
    description: "Python version to use"
    default: "3.x"
  requirements-file:
    description: "Path to the requirements file"
    default: "requirements.txt"

runs:
  using: "composite"
  steps:
    - name: 🛠️ Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: 💾 Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ hashFiles(inputs.requirements-file) }}
        restore-keys: |
          pip-cache-

    - name: 📦 Install dependencies from requirements file
      run: pip install -r ${{ inputs.requirements-file }}
      shell: bash
