---
- name: Fake capabilities to prevent unwanted swapoff  # noqa var-naming
  ansible.builtin.set_fact:
    ansible_system_capabilities_enforced: true
    ansible_system_capabilities: []

- name: Include debops.debops.swapfile role with custom vars
  ansible.builtin.include_role:
    name: debops.debops.swapfile
  vars:
    swapfile__files:
      - path: /swapfile
        size: 4096
        state: present

- name: Get active swap info
  ansible.builtin.command: swapon --noheadings --bytes --show=SIZE
  register: swapfile_status
  changed_when: false

- name: Enable all swap devices if none are active
  ansible.builtin.command: swapon --all --verbose
  when: swapfile_status.stdout_lines | map('int') | sum == 0
  changed_when: true

- name: Refresh system facts to restore capability info
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - 'min'
