#!/bin/sh

# Detect top-level folders dynamically
get_top_level_folders() {
	doveadm mailbox list -u "$mailbox_user" |
		cut -d. -f1 |
		sort -u
}

# Capitalize first letter, lowercase the rest
format_label() {
	printf "%s" "$1" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}'
}

output_config() {
  get_top_level_folders | while read -r folder; do
    safe_name=$(echo "$folder" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '_')
    label=$(format_label "$folder")
    echo "${safe_name}.label $label"
  done

	cat <<'EOM'
graph_args --base 1024 --lower-limit 0
graph_scale yes
graph_category email
graph_title Mail folder sizes (with subfolders)
graph_info Size of each folder including subfolders
graph_vlabel Size
EOM
}

output_values() {
	get_top_level_folders | while read -r folder; do
		safe_name=$(echo "$folder" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '_')
		size=$(mailbox_vsize "$folder")
		echo "${safe_name}.value $size"
	done
}

mailbox_vsize() {
	parent="$1"
	doveadm mailbox list -u "$mailbox_user" |
		awk -v f="$parent" '$1 == f || $1 ~ "^"f"\\."' |
		xargs -r -I{} doveadm -f tab mailbox status -u "$mailbox_user" vsize '{}' |
		awk '{sum += $2} END {print sum}'
}

output_usage() {
	printf >&2 "%s - munin plugin to graph size of mailboxes (with subfolders)\n" "${0##*/}"
	printf >&2 "Usage: %s [config]\n" "${0##*/}"
}

case $# in
0)
	output_values
	;;
1)
	case $1 in
	config)
		output_config
		;;
	*)
		output_usage
		exit 1
		;;
	esac
	;;
*)
	output_usage
	exit 1
	;;
esac
