---
- name: Check WordPress theme {{ wp_theme }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - is-installed
      - "{{ wp_theme }}"
      - "--path={{ webserver_directory }}"
  changed_when: false
  failed_when: false
  register: wp_theme_is_installed

- name: Install WordPress theme {{ wp_theme }}
  when: wp_theme_is_installed.rc | int != 0
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - install
      - "{{ wp_theme }}"
      - --activate
      - "--path={{ webserver_directory }}"
  changed_when: true

- name: Check if auto-updates are disabled for {{ wp_theme }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - auto-updates
      - status
      - "{{ wp_theme }}"
      - "--path={{ webserver_directory }}"
      - "--disabled-only"
      - "--field=name"
  changed_when: false
  register: wp_theme_auto_updates

- name: Enable auto-updates if disabled for {{ wp_plugin }}
  when: wp_theme_auto_updates.stdout | trim == wp_theme
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - auto-updates
      - enable
      - "{{ wp_theme }}"
      - "--path={{ webserver_directory }}"
  changed_when: true
