---
- name: Check WordPress theme {{ wp_theme }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp theme is-installed
        {{ wp_theme }}
        --path={{ webserver_directory }}
  changed_when: false
  failed_when: false
  register: wp_theme_is_installed

- name: Install WordPress theme {{ wp_theme }}
  when: wp_theme_is_installed.rc | int != 0
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp theme install
        {{ wp_theme }}
        --activate
        --path={{ webserver_directory }}
  changed_when: true

- name: Check the status of auto-updates for {{ wp_theme }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp theme auto-updates status
        {{ wp_theme }}
        --path={{ webserver_directory }}
  changed_when: false
  failed_when: false
  register: wp_theme_auto_updates

- name: Enables the auto-updates for {{ wp_theme }}
  when: wp_theme_auto_updates.rc | int != 0
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp theme auto-updates enable
        {{ wp_theme }}
        --path={{ webserver_directory }}
  changed_when: true
