---
- name: Check WordPress plugin {{ wp_plugin }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp plugin is-installed
        {{ wp_plugin }}
        --path={{ webserver_directory }}
  changed_when: false
  failed_when: false
  register: wp_plugin_is_installed

- name: Install WordPress plugin {{ wp_plugin }}
  when: wp_plugin_is_installed.rc | int != 0
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp plugin install
        {{ wp_plugin }}
        --activate
        --path={{ webserver_directory }}
  changed_when: true
