---
- name: Ensure WordPress theme is installed - {{ wp_theme }}
  when: wp_theme_is_installed.rc | int != 0
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - install
      - "{{ wp_theme }}"
      - --activate
      - "--path={{ webserver_directory }}"
  register: wp_theme_install
  changed_when: "'Installing' in wp_theme_install.stdout"

- name: Ensure auto-updates are enabled for {{ wp_theme }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - auto-updates
      - enable
      - "{{ wp_theme }}"
      - "--path={{ webserver_directory }}"
  register: wp_theme_autoupdate
  changed_when: "'Success' in wp_theme_autoupdate.stdout"
