---
- name: Activate fallback theme
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - activate
      - "{{ blog_wp_themes_fallback }}"
      - "--path={{ webserver_directory }}"
  register: wp_theme_activate_fallback
  failed_when: false
  changed_when: "'Success' in wp_theme_activate_fallback.stdout"

- name: Uninstall WordPress theme {{ wp_theme }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - delete
      - "{{ wp_theme }}"
      - "--path={{ webserver_directory }}"
  register: wp_theme_remove
  failed_when: >
    wp_theme_remove.rc != 0 and
    (
      'not found' not in (wp_theme_remove.stderr | lower) and
      'is not installed' not in (wp_theme_remove.stderr | lower) and
      'could not be found' not in (wp_theme_remove.stderr | lower)
    )
  changed_when: "'Deleted' in wp_theme_remove.stdout"
