---
- name: Ensure WordPress plugin is installed - {{ wp_plugin }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - install
      - "{{ wp_plugin }}"
      - --activate
      - "--path={{ webserver_directory }}"
  register: wp_plugin_install
  changed_when: "'Installing' in wp_plugin_install.stdout"

- name: Ensure auto-updates are enabled for {{ wp_plugin }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - auto-updates
      - enable
      - "{{ wp_plugin }}"
      - "--path={{ webserver_directory }}"
  register: wp_plugin_autoupdate
  changed_when: "'Success' in wp_plugin_autoupdate.stdout"
