---
- name: Check if wp-config-sample.php exists
  ansible.builtin.stat:
    path: "{{ webserver_directory }}/wp-config-sample.php"
  register: wp_config_sample

- name: Download WordPress
  when: not wp_config_sample.stat.exists
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp core download
        --path={{ webserver_directory }}
  register: wp_core_download
  changed_when: true

- name: Check if wp-config.php exists
  ansible.builtin.stat:
    path: "{{ webserver_directory }}/wp-config.php"
  register: wp_config

- name: Create a new wp-config.php
  when: not wp_config.stat.exists
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp config create
        --dbname={{ blog_wp_db_name }}
        --dbuser={{ blog_wp_db_user }}
        --dbpass={{ blog_wp_db_password }}
        --dbhost={{ blog_wp_db_host }}
        --path={{ webserver_directory }}
  register: wp_core_download
  changed_when: true

- name: Install WordPress themes
  ansible.builtin.include_tasks:
    file: wordpress_themes_install.yml
  loop: "{{ blog_wp_themes_install }}"
  loop_control:
    loop_var: wp_theme

- name: Install WordPress plugins
  ansible.builtin.include_tasks:
    file: wordpress_plugins_install.yml
  loop: "{{ blog_wp_plugins_install }}"
  loop_control:
    loop_var: wp_plugin

- name: Uninstall WordPress themes
  ansible.builtin.include_tasks:
    file: wordpress_themes_uninstall.yml
  loop: "{{ blog_wp_themes_uninstall }}"
  loop_control:
    loop_var: wp_theme

- name: Uninstall WordPress plugins
  ansible.builtin.include_tasks:
    file: wordpress_plugins_uninstall.yml
  loop: "{{ blog_wp_plugins_uninstall }}"
  loop_control:
    loop_var: wp_plugin

- name: Create directory /tmp/wp-content
  ansible.builtin.file:
    path: /tmp/wp-content
    state: directory
    mode: u=rwx,go=rx

- name: Get WordPress uploads from S3
  amazon.aws.s3_object:
    bucket: backups-by-amedee
    object: wp-content/uploads.tar.xz
    dest: /tmp/wp-content/uploads.tar.xz
    mode: get
    overwrite: different
    access_key: "{{ common_aws_access_key }}"
    secret_key: "{{ common_aws_secret_key }}"
    region: us-east-1

- name: Extract WordPress uploads on the remote machine
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/wp-content/uploads.tar.xz
    dest: "{{ webserver_directory }}/wp-content/"
    owner: "{{ webserver_user }}"
