---
- name: Deactivate and uninstall WordPress plugin {{ wp_plugin }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - deactivate
      - "{{ wp_plugin }}"
      - --uninstall
      - "--path={{ webserver_directory }}"
  register: wp_plugin_remove
  failed_when: >
    wp_plugin_remove.rc != 0 and
    (
      'not found' not in wp_plugin_remove.stderr | lower and
      'is not installed' not in wp_plugin_remove.stderr | lower and
      'could not be found' not in wp_plugin_remove.stderr | lower
    )
  changed_when: "'Success: Uninstalled' in wp_plugin_deactivate.stdout"
