---
- name: Check if WP-CLI is already installed
  ansible.builtin.stat:
    path: "{{ blog_wpcli_path }}"
  register: wpcli

- name: Download WP-CLI
  when: not wpcli.stat.exists
  become: true
  ansible.builtin.get_url:
    url: "{{ blog_wpcli_url }}" # checkov:skip=Checkov_CKV2_ANSIBLE_2:The URL in the variable uses HTTPS
    dest: "{{ blog_wpcli_path }}"
    owner: root
    mode: u=rwx,go=rx

- name: Check if installed WP-CLI is at the latest version
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    cmd: >
      wp cli check-update
        --format=table
        --no-color
  register: wp_cli_checkupdate
  changed_when: false
  failed_when: false

- name: Debug wp cli check-update
  ansible.builtin.debug:
    var: wp_cli_checkupdate.stdout

- name: Update WP-CLI
  when: not "Success" in wp_cli_checkupdate.stdout
  become: true
  ansible.builtin.command:
    cmd: >
      wp cli update
        --yes
        --allow-root
  register: wp_cli_update
  changed_when: true
