---
- name: APT update
  ansible.builtin.apt:
    update_cache: true
  retries: 10
  delay: 5
  register: apt_result
  until: apt_result is succeeded

- name: APT autoclean
  ansible.builtin.apt:
    autoclean: true

- name: APT autoremove
  ansible.builtin.apt:
    autoremove: true
