---
# created by 'IntelliJ Ansible Lint Plugin'
#
# check this website for detailed configuration options:
#    https://ansible-lint.readthedocs.io/configuring/#ansible-lint-configuration

profile: production

exclude_paths:
  - '**/roles/geerlingguy.munin-node/'
  - '**/roles/geerlingguy.swap/'
  - '**/roles/rolehippie.swap/'
