---
# @meta author:value: [Amedee Van Gasse](https://amedee.be)
galaxy_info:
  description: Wrapper role for `debops.debops.swapfile` because it doesn't run `swapon --all`.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
