---
- name: Block broken Duplicity versions from installing
  ansible.builtin.copy:
    src: pin_duplicity.pref
    dest: /etc/apt/preferences.d/pin_duplicity.pref
    owner: root
    group: root
    mode: "0644"

- name: Install Duplicity
  ansible.builtin.apt:
    name:
      - duplicity

- name: Create Duplicity config directory
  ansible.builtin.file:
    path: /home/user-data/backup
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Check if backup.py exists
  ansible.builtin.stat:
    path: /root/mailinabox/management/backup.py
  register: mailinabox_duplicity_backup_py

- name: Configure Duplicity
  ansible.builtin.template:
    src: custom.yaml.j2
    dest: /home/user-data/backup/custom.yaml
    owner: root
    group: root
    mode: "0600"
  no_log: true
  notify: Perform backup

- name: Create apt-backup-duplicity.sh script
  ansible.builtin.copy:
    src: apt-backup-duplicity.sh
    dest: /usr/local/bin/apt-backup-duplicity.sh
    owner: root
    group: root
    mode: "0755"

- name: Create APT Post-Invoke hook to run backup script
  ansible.builtin.copy:
    src: 99backup-duplicity-debs
    dest: /etc/apt/apt.conf.d/99backup-duplicity-debs
    owner: root
    group: root
    mode: "0644"
