---
- name: Create duplicity config directory
  ansible.builtin.file:
    path: /home/user-data/backup
    state: directory
    owner: root
    mode: u=rw,go=r

- name: Check if backup.py exists
  ansible.builtin.stat:
    path: /root/mailinabox/management/backup.py
  register: mailinabox_duplicity_backup_py

- name: Configure duplicity
  ansible.builtin.template:
    src: custom.yaml.j2
    dest: /home/user-data/backup/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: Perform backup
