---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Create DNS directory
      ansible.builtin.file:
        path: /home/user-data/dns
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create Mail-in-a-Box tools directory
      ansible.builtin.file:
        path: /root/mailinabox/tools
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create dummy DNS update script
      ansible.builtin.copy:
        content: |
          #!/bin/sh
          echo "$@" >> /tmp/dns-update-calls
        dest: /root/mailinabox/tools/dns_update
        owner: root
        group: root
        mode: "0755"
