---
- name: Verify custom DNS role behavior
  hosts: all
  gather_facts: false

  tasks:
    - name: Verify DNS update was called
      ansible.builtin.stat:
        path: /tmp/dns-update-was-called
      register: mailinabox_dns_update_called

    - name: Assert DNS update was called
      ansible.builtin.assert:
        that:
          - mailinabox_dns_update_called.stat.exists
