---
wp_archive_dir: /var/cache/wp-archive
wp_archive: "{{ wp_archive_dir }}/uploads.tar.xz"

wp_packages:
  - curl
  - ghostscript
  - imagemagick
  - mysql-client

wp_php_packages:
  - php-cli
  - php-curl
  - php-gd
  - php-imagick
  - php-intl
  - php-json
  - php-mbstring
  - php-mysql
  - php-redis
  - php-ssh2
  - php-xml
  - php-xmlrpc
  - php-zip

wp_python_packages:
  - python3-boto3
  - python3-packaging
  - python3-pip
  - python3-pymysql

wp_constants:
  - name: WP_CACHE_KEY_SALT
    value: localhost

wp_plugins:
  - redis-cache
  - wp-redis
wp_plugins_uninstall:
  - hello
wp_themes:
  - neve
wp_themes_uninstall:
  - twentytwentytwo
  - twentytwentythree
  - twentytwentyfour
wp_fallback_theme: neve

wp_table_prefix: wp_
wp_db_name: wordpress
wp_db_user: wordpress
wp_db_host: localhost
wp_db_password: ""
wp_database_constants:
  DB_NAME: "{{ wp_db_name }}"
  DB_USER: "{{ wp_db_user }}"
  DB_PASSWORD: "{{ wp_db_password }}"
  DB_HOST: "{{ wp_db_host }}"

wp_webserver_user: "{{ webserver_user | default('www-data') }}"
wp_webserver_directory: "{{ webserver_directory | default('/var/www/html') }}"
wp_site_url: "http://localhost"
wp_site_title: "WordPress"
wp_admin_user: "admin"
wp_admin_password: "admin-password" # pragma: allowlist secret
wp_admin_email: "admin@example.com"

wp_php_bin: "/usr/bin/php"
wp_cli_bin: "/usr/local/bin/wp"
wp_cli:
  - "{{ wp_php_bin }}"
  - "{{ wp_cli_bin }}"
  - "--path={{ wp_webserver_directory }}"
