---
- name: Create custom DNS directory
  ansible.builtin.file:
    path: /home/user-data/dns
    state: directory
    owner: root
    mode: u=rw,go=r

- name: Check if dns_update exists
  ansible.builtin.stat:
    path: /root/mailinabox/tools/dns_update
  register: mailinabox_dns_update

- name: Copy custom DNS settings
  ansible.builtin.copy:
    src: custom.yaml
    dest: /home/user-data/dns/custom.yaml
    owner: root
    mode: "0644"
  notify: DNS update
