---
- name: Prepare
  hosts: all
  become: true

  vars:
    letsencrypt_restore_enabled: false
    nginx_ssl_enabled: false
    keyring__dependent_gpg_keys:
      - id: 63AF7AA15067C05616FDDD88A3A2E8F226F0BC06
    wpcli__version: "2.12.0"
    wpcli__release_files:
      - url: 'https://github.com/wp-cli/wp-cli/releases/download/v2.12.0/wp-cli-2.12.0.phar.gpg'
        dest: '{{ wpcli__src }}/wp-cli-2.12.0.phar.gpg'
        checksum: 'sha256:f12126a3ca1c48e53b7f89fd30e60b9cf3335dfb0c94403a2e5c125be0e66c77'
        version: '2.12.0'
      - url: 'https://raw.githubusercontent.com/wp-cli/wp-cli/v2.12.0/utils/wp-completion.bash'
        dest: '{{ wpcli__src }}/wp-cli-2.12.0.completion.bash'
        checksum: 'sha256:443ca0610ccae8d2d6aceba0ec4aa7929b87ed6cf54f666afed18d663a18a395'
        version: '2.12.0'

  roles:
    - mysql
    - redis
    - letsencrypt
    - nginx
    - debops.debops.keyring
    - debops.debops.wpcli
