---
- name: Gather installed package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Hold all "grub-" packages (only in staging)
  ansible.builtin.command: "apt-mark hold {{ item }}"
  with_items: "{{ ansible_facts.packages.keys() | select('match', '^grub-') | list }}"
  when:
    - hold_grub_packages | default(false)
    - item in ansible_facts.packages
    - "'hold' not in ansible_facts.packages[item]"
  changed_when: true

- name: Remove unneeded APT packages
  ansible.builtin.apt:
    state: absent
    pkg: "{{ common_apt_packages_uninstall }}"
  notify:
    - APT autoclean
    - APT autoremove
    - Check if reboot required

- name: Install APT packages
  ansible.builtin.apt:
    state: present
    pkg: "{{ common_apt_packages }}"
  notify:
    - APT autoclean
    - APT autoremove
    - Check if reboot required

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  notify:
    - APT autoclean
    - APT autoremove
    - Check if reboot required

- name: Install snap packages
  community.general.snap:
    name: "{{ common_snap_packages }}"
