---
- name: Wait for APT locks to be released using flock
  ansible.builtin.command:
    argv:
      - /usr/bin/flock
      - --wait
      - "300"
      - /var/lib/apt/lists/lock
      - /var/lib/dpkg/lock
      - /var/lib/dpkg/lock-frontend
      - "true"
  changed_when: false
  failed_when: false

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400 # One day
  register: result
  retries: 3
  delay: 60
  until: result is not failed

- name: Configure locale
  ansible.builtin.import_tasks: locale.yml

- name: Install and upgrade software
  ansible.builtin.import_tasks: install_software.yml

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Allow Munin access to port 4949
  community.general.ufw:
    rule: allow
    port: 4949
    src: 142.93.227.16
