---
- name: Configure locale
  block:
    - name: Ensure locale exists
      community.general.locale_gen:
        name: "{{ common_locale }}"
        state: present

    - name: Install localepurge packages
      ansible.builtin.apt:
        state: present
        pkg: localepurge

    - name: Edit localepurge config file
      ansible.builtin.lineinfile:
        path: /etc/locale.nopurge
        create: true
        line: "{{ common_locale }}"
        owner: root
        mode: u=rw,go=r

- name: Install and upgrade software
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
      register: result
      retries: 3
      delay: 60
      until: result is not failed

    - name: Remove unneeded APT packages
      ansible.builtin.apt:
        state: absent
        pkg: "{{ common_apt_packages_uninstall }}"
      notify:
        - APT autoclean
        - APT autoremove
        - Check if reboot required

    - name: Install APT packages
      ansible.builtin.apt:
        state: present
        pkg: "{{ common_apt_packages }}"
      notify:
        - APT autoclean
        - APT autoremove
        - Check if reboot required

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      notify:
        - APT autoclean
        - APT autoremove
        - Check if reboot required

    - name: Install snap packages
      community.general.snap:
        name: "{{ common_snap_packages }}"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Configure Munin
  block:
    - name: Add mailinabox IP address to munin-node.conf
      ansible.builtin.lineinfile:
        path: /etc/munin/munin-node.conf
        line: allow ^142\.93\.227\.16$
        insertafter: "^allow .*"
        owner: root
        mode: u=rw,go=r
      notify: Restart munin-node

    - name: Copy munin plugin config files
      ansible.builtin.copy:
        src: etc/munin/plugin-conf.d/
        dest: /etc/munin/plugin-conf.d/
        owner: root
        mode: u=rw,go=r
        directory_mode: u=rwx,go=rx
      notify: Restart munin-node

    - name: Allow access to port 4949
      community.general.ufw:
        rule: allow
        port: 4949
        src: 142.93.227.16
      notify: Restart munin-node
