---
- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist
    autoclean: true
    autoremove: true
  notify: Check if reboot required
