---
- name: Install and upgrade software
  become: true
  block:
    - name: Copy daily cron job for apt-get update
      ansible.builtin.copy:
        src: etc/cron.daily/apt-get_update.sh
        dest: /etc/cron.daily/apt-get_update.sh
        owner: root
        mode: u=rwx,go=r

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400 # One day
      register: result
      retries: 3
      delay: 60
      until: result is not failed

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      notify:
        - APT autoclean
        - APT autoremove
        - Check if reboot required

    - name: Install APT packages
      ansible.builtin.apt:
        state: present
        pkg: "{{ common_apt_packages }}"
      notify: Check if reboot required

    - name: Install snap packages
      community.general.snap:
        name: "{{ common_snap_packages }}"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Configure Munin
  become: true
  block:
    - name: Add mailinabox IP address to munin-node.conf
      ansible.builtin.lineinfile:
        path: /etc/munin/munin-node.conf
        line: allow ^142\.93\.227\.16$
        insertafter: "^allow .*"
        owner: root
        mode: u=rw,go=r
      notify: Restart munin-node

    - name: Allow access to port 4949
      community.general.ufw:
        rule: allow
        port: 4949
        src: 142.93.227.16
      notify: Restart munin-node

    - name: Exclude loop devices from Munin df and diskstats plugin
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/munin/plugin-conf.d/
        owner: root
        mode: u=rw,go=r
      with_fileglob: "etc/munin/plugin-conf.d/zzz_*"
      notify: Restart munin-node

- name: Copy monthly cron job for hadori
  become: true
  ansible.builtin.copy:
    src: etc/cron.monthly/hadori.sh
    dest: /etc/cron.monthly/hadori.sh
    owner: root
    mode: u=rwx,go=r
