---
name: "AI Commit Message Generator"
description: "Generate concise AI-powered git commit message"

inputs:
  diff_content:
    description: "Diff content string to use for commit message generation"
    required: true
  prompt_content:
    description: "Prompt message describing what the AI should do"
    required: true
  models:
    required: false
    description: "Comma-separated list of OpenRouter models"
    default: >
      google/gemma-3-27b-it:free,
      meta-llama/llama-3.3-70b-instruct:free,
      mistralai/mistral-small-3.1-24b-instruct:free,
      openai/gpt-oss-20b:free,
      deepseek/deepseek-r1-0528:free,
      openrouter/aurora-alpha,
      arcee-ai/trinity-large-preview:free

outputs:
  message:
    description: "Generated commit message"

runs:
  using: "node20"
  main: "dist/index.js"
