---
- name: Install a list of packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    pkg: "{{ dbserver_packages }}"

- name: Start and enable mysql service
  become: true
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create a new database with name 'wordpress'
  become: true
  community.mysql.mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
