---
- name: Disable binary logging in MySQL
  community.general.ini_file:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    section: mysqld
    option: disable_log_bin
    allow_no_value: true
    owner: root
    mode: u=rw,go=r
  notify: Restart mysql
