---
- name: Update Postfix hashtables
  ansible.builtin.command:
    chdir: /etc/postfix/sasl
    cmd: postmap sasl_passwd
  register: postmap_output
  changed_when: true
  notify: Restart Postfix

- name: Restart Postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Build Postfix transport
  ansible.builtin.command:
    cmd: postmap /etc/postfix/transport
  changed_when: false
  notify: Reload Postfix

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
