---
- name: Update Postfix hashtables
  become: true
  ansible.builtin.command:
    chdir: /etc/postfix/sasl
    cmd: postmap sasl_passwd
  register: postmap_output
  changed_when: false
  listen: Update Postfix hashtables
  notify: Restart Postfix

- name: Restart Postfix
  become: true
  ansible.builtin.service:
    name: postfix
    state: restarted
  listen: Restart Postfix

- name: Restart Rsyslog
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  listen: Restart Rsyslog
