---
# @meta author:value: [Amedee Van Gasse](https://amedee.be)
galaxy_info:
  description: Role to install boto for communication with AWS.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - noble
