---
dependencies:
  - role: common
  - role: debops.debops.logrotate
    logrotate__options: |
      su root adm
    logrotate__config:
      - filename: postfix
        logs:
          - /var/log/mail.log
          - /var/log/mail.err
        options: |
          monthly
          rotate 24
          missingok
          notifempty
          compress
          delaycompress
          extension log
          create 0644 root root
          sharedscripts
        postrotate: |
          systemctl restart rsyslog
          systemctl restart postfix
