---
galaxy_info:
  description: Role to configure my mailservers.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies:
  - role: common
  - role: debops.debops.logrotate
    logrotate__options: |
      su root adm
    logrotate__config:
      - filename: postfix
        logs:
          - /var/log/mail.log
          - /var/log/mail.err
        options: |
          monthly
          rotate 24
          missingok
          notifempty
          compress
          delaycompress
          extension log
          create 0644 root root
          sharedscripts
        postrotate: |
          systemctl restart rsyslog
          systemctl restart postfix
