---
dependencies:
  - role: mailserver
  - role: debops.debops.apt_preferences
    apt_preferences__list:
      - package: 'duplicity'
        version: '3.0.1'
        priority: '-1'
        reason: |-
          Duplicity version 3.0.1 has a bug and I don't want it installed
  - role: debops.debops.cron
    cron__jobs:
      doveadm_expunge:
        jobs:
          - name: 'Expunge Trash'
            special_time: 'daily'
            job: '/usr/bin/doveadm expunge -A mailbox Trash before 30d'
          - name: 'Expunge Spam'
            special_time: 'daily'
            job: '/usr/bin/doveadm expunge -A mailbox Spam before 30d'
      extract_image_attachments:
        name: 'Extract image attachments'
        special_time: 'daily'
        job: '/usr/local/bin/extract_image_attachments.sh'
        custom_files:
          - src: 'usr/local/bin/extract_image_attachments.sh'
            dest: '/usr/local/bin/extract_image_attachments.sh'
            owner: root
            mode: u=rwx,go=rx
  - role: geerlingguy.munin-node
    munin_node_allowed_ips:
      - '^127\.0\.0\.1$'
      - '^::1$'
      - '^142\.93\.227\.16$'
    munin_node_config: {
      "backup_size": {
        "user": "root"
      },
      "mailbox_*": {
        "user": "root",
        "env.mailbox_user": "amedee@vangasse.eu"
      }
    }
    munin_node_install_plugins:
      - src: files/etc/munin/plugins/backup_size
      - src: files/etc/munin/plugins/mailbox_messages
      - src: files/etc/munin/plugins/mailbox_size
