---
dependencies:
  - role: debops.debops.apt_preferences
    apt_preferences__list:
      - package: 'duplicity'
        reason: |-
          Duplicity version 3.0.1 has a bug and I don't want it installed
        version: '3.0.1'
        priority: '99'
  - role: mailserver
