---
# @meta author:value: [Amedee Van Gasse](https://amedee.be)
galaxy_info:
  description: Role to do post-install configuration of mailinabox.
  author: Amedee Van Gasse
  license: MIT
  min_ansible_version: "2.1"
  namespace: amedee
  platforms:
    - name: Ubuntu
      versions:
        - jammy

dependencies:
  - role: mailserver
  - role: geerlingguy.munin-node
    munin_node_config:
      backup_size:
        user: root
      "mailbox_*":
        user: root
        env.mailbox_user: amedee@vangasse.eu
    munin_node_install_plugins:
      - src: usr/share/munin/plugins/backup_size
      - src: usr/share/munin/plugins/mailbox_base.py
      - src: usr/share/munin/plugins/mailbox_messages.py
      - src: usr/share/munin/plugins/mailbox_vsize.py
    munin_node_plugins:
      - name: backup_size
      - name: mailbox_messages
        plugin: mailbox_messages.py
      - name: mailbox_vsize
        plugin: mailbox_vsize.py
