---
- name: "Cleanup {{ webserver_directory }}"
  become: true
  ansible.builtin.file:
    path: "{{ webserver_directory }}/{{ item }}"
    state: absent
  loop: "{{ webserver_default_indexfiles }}"

- name: "Change permissions of {{ webserver_directory }}"
  become: true
  ansible.builtin.file:
    path: "{{ webserver_directory }}"
    owner: www-data
    group: www-data
    recurse: true
    # supposed to set directories to 755 and files to 644
    mode: u=rwX,go=rX
