---
- name: Ensure software is installed
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    pkg: "{{ webserver_packages }}"

- name: Check if latest version of WP-CLI is installed
  ansible.builtin.import_tasks: wpcli.yml

- name: "Install WordPress in {{ webserver_directory }}"
  ansible.builtin.import_tasks: wordpress.yml

- name: "Set defaults on {{ webserver_directory }}"
  ansible.builtin.import_tasks: htmldir.yml
