---
- name: Add ondrej repositories
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    uris: "{{ item.repo.uris }}"
    suites: "{{ item.repo.suites }}"
    components: "{{ item.repo.components }}"
    signed_by: "{{ item.repo.signed_by }}"
  loop: "{{ webserver_deb822_repositories }}"

- name: Install APT packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400  # One day
    pkg: "{{ webserver_apt_packages }}"

- name: Copy website config files
  ansible.builtin.copy:
    src: etc/nginx/
    dest: /etc/nginx/
    owner: root
    mode: u=rw,go=r
    directory_mode: u=rwx,go=rx
  notify: Restart nginx

- name: Delete DigitalOcean website config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/digitalocean
    state: absent
  notify: Restart nginx

- name: Create a symbolic link
  ansible.builtin.file:
    src: /etc/nginx/sites-available/amedee.be
    dest: /etc/nginx/sites-enabled/default
    owner: root
    state: link
  notify: Restart nginx

- name: "Check existence of webserver directory {{ webserver_directory }}"
  ansible.builtin.file:
    path: "{{ webserver_directory }}"
    state: directory
    owner: "{{ webserver_user }}"
    group: "{{ webserver_user }}"
    mode: u=rwx,go=rx

- name: Install and configure Letsencrypt
  ansible.builtin.import_tasks: letsencrypt.yml

- name: Configure Redis
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    create: true
    owner: root
    mode: u=rw,go=r
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ webserver_redis_settings }}"
  notify: Restart redis
