---
- name: Ensure software is installed
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    pkg: "{{ webserver_packages }}"

- name: Copy website config files
  become: true
  ansible.builtin.copy:
    src: sites-available/amedee.be
    dest: /etc/nginx/sites-available/amedee.be
    owner: root
    mode: u=rw,go=r
  notify: Restart nginx

- name: Delete DigitalOcean website config
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/digitalocean
    state: absent
  notify: Restart nginx

- name: Create a symbolic link
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/amedee.be
    dest: /etc/nginx/sites-enabled/default
    owner: root
    state: link
  notify: Restart nginx

- name: Install and configure Letsencrypt
  ansible.builtin.import_tasks: letsencrypt.yml

- name: Check if latest version of WP-CLI is installed
  ansible.builtin.import_tasks: wpcli.yml

- name: "Install WordPress in {{ webserver_directory }}"
  ansible.builtin.import_tasks: wordpress.yml

- name: "Set defaults on {{ webserver_directory }}"
  ansible.builtin.import_tasks: htmldir.yml
