---
- name: Ensure software is installed
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    pkg: "{{ webserver_packages }}"
  tags:
    - install
