---
- name: Install APT packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    state: present
    pkg: "{{ webserver_apt_packages }}"

- name: Copy website config files
  become: true
  ansible.builtin.copy:
    src: etc/nginx/sites-available/amedee.be
    dest: /etc/nginx/sites-available/amedee.be
    owner: root
    mode: u=rw,go=r
  notify: Restart nginx

- name: Delete DigitalOcean website config
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/digitalocean
    state: absent
  notify: Restart nginx

- name: Create a symbolic link
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/amedee.be
    dest: /etc/nginx/sites-enabled/default
    owner: root
    state: link
  notify: Restart nginx

- name: "Check existence of webserver directory {{ webserver_directory }}"
  become: true
  ansible.builtin.file:
    path: "{{ webserver_directory }}"
    state: directory
    owner: "{{ webserver_user }}"
    group: "{{ webserver_user }}"
    mode: u=rwx,go=rx

- name: Install and configure Letsencrypt
  ansible.builtin.import_tasks: letsencrypt.yml
