---
- name: "Check existence of webserver directory {{ webserver_directory }}"
  become: true
  ansible.builtin.file:
    path: "{{ webserver_directory }}"
    state: directory
    owner: www-data
    group: www-data
    mode: u=rwx,go=rx

- name: Check if wp-config-sample.php exists
  ansible.builtin.stat:
    path: "{{ webserver_directory }}/wp-config-sample.php"
  register: wp_config_sample

- name: Download WordPress
  when: not wp_config_sample.stat.exists
  become: true
  ansible.builtin.command:
    cmd: >
      wp core download
        --path={{ webserver_directory }}
        --allow-root
  register: wp_core_download
  changed_when: true

- name: Check if wp-config.php exists
  ansible.builtin.stat:
    path: "{{ webserver_directory }}/wp-config.php"
  register: wp_config

- name: Load WordPress db variables
  when: not wp_config.stat.exists
  ansible.builtin.include_vars:
    file: ../../dbserver/vars/wordpress.yml

- name: Create a new wp-config.php
  when: not wp_config.stat.exists
  become: true
  ansible.builtin.command:
    cmd: >
      wp config create
        --dbname={{ dbserver_wp_db_name }}
        --dbuser={{ dbserver_wp_db_user }}
        --dbpass={{ dbserver_wp_db_password }}
        --dbhost={{ dbserver_wp_db_host }}
        --path={{ webserver_directory }}
        --allow-root
  register: wp_core_download
  changed_when: true

- name: "Install theme {{ webserver_wp_theme }}"
  become: true
  ansible.builtin.command:
    cmd: >
      wp theme install
        {{ webserver_wp_theme }}
        --activate
        --path={{ webserver_directory }}
        --allow-root
  register: wp_theme_install
  changed_when: true

- name: Install WordPress plugins
  become: true
  ansible.builtin.command:
    cmd: >
      wp plugin install
        {{ item }}
        --activate
        --path={{ webserver_directory }}
        --allow-root
  loop: "{{ webserver_wp_plugins }}"
  register: wp_plugin_install
  changed_when: true
