---
- name: Install munin-node and software required by some plugins
  ansible.builtin.apt:
    name:
      - hping3
      - munin-node
      - uptimed

- name: Allow munin-node to read files in home directories
  community.general.ini_file:
    path: /lib/systemd/system/munin-node.service
    section: Service
    option: ProtectHome
    value: false
    ignore_spaces: true
    no_extra_spaces: true
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart munin-node

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw

- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled

- name: Allow Munin access to port 4949
  community.general.ufw:
    rule: allow
    port: 4949
    src: 142.93.227.16
