---
- name: Allow munin-node to read files in home directories
  community.general.ini_file:
    path: /lib/systemd/system/munin-node.service
    section: Service
    option: ProtectHome
    value: false
    ignore_spaces: true
    no_extra_spaces: true
    owner: root
    mode: u=rw,go=r
  notify:
    - Reload systemd
    - Restart munin-node

- name: Allow Munin access to port 4949
  community.general.ufw:
    rule: allow
    port: 4949
    src: 142.93.227.16
