---
- name: Add munin host configurations
  ansible.builtin.copy:
    src: munin-conf.d/
    dest: /etc/munin/munin-conf.d/
    owner: root
    group: root
    mode: "0644"
  notify: Restart munin

- name: Remove duplicate munin host configuration
  community.general.ini_file:
    path: /etc/munin/munin.conf
    section: box.vangasse.eu
    state: absent
    owner: root
    group: root
    mode: "0644"
  notify: Restart munin
