---
- name: Add munin host configurations
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/munin/munin-conf.d/
    owner: root
    mode: '0644'
  with_fileglob: "*"
  notify: Restart munin

- name: Remove duplicate munin host configuration
  community.general.ini_file:
    path: /etc/munin/munin.conf
    section: box.vangasse.eu
    state: absent
    owner: root
    mode: u=rw,go=r
  notify: Restart munin
