---
- name: Uninstall apt Certbot (old version)
  ansible.builtin.apt:
    name:
      - apache2
      - apache2-bin
      - certbot
    state: absent
    autoremove: true

- name: Install snap Certbot (new version)
  community.general.snap:
    name: certbot
    classic: true

- name: Create Certbot symlink
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
