---
- name: Install LetsEncrypt
  ansible.builtin.import_tasks: install.yml

- name: Restore LetsEncrypt configuration
  ansible.builtin.import_tasks: restore.yml
  when: letsencrypt_restore_from_backup
