---
- name: Ensure duplicity is installed
  ansible.builtin.apt:
    name: duplicity
    state: present

- name: Configure duplicity
  ansible.builtin.template:
    src: home/user-data/backup/custom.yaml.j2
    dest: /home/user-data/backup/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: Perform backup
