---
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Ensure UFW is enabled
  ansible.builtin.command: ufw enable
  when: ansible_facts['os_family'] == 'Debian'
  ignore_errors: true
  register: ufw_enable_output
  changed_when: ufw_enable_output.rc != 0

- name: Add NAT rule to before.rules
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    backup: true
    insertafter: '^COMMIT'
    block: |
      *nat
      :POSTROUTING ACCEPT [0:0]
      # Redirect outgoing SMTP traffic (port 25) to localhost
      -A OUTPUT -p tcp --dport 25 -j DNAT --to-destination 127.0.0.1:25
      COMMIT

- name: Ensure DEFAULT_FORWARD_POLICY is set to ACCEPT
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Ensure IP_FORWARD is set to yes
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^IP_FORWARD='
    line: 'IP_FORWARD="yes"'

- name: Reload UFW
  ansible.builtin.command: ufw reload
  ignore_errors: true
  register: ufw_reload_output
  changed_when: ufw_reload_output.rc != 0
