---
- name: Add cron job to expunge Trash
  ansible.builtin.cron:
    cron_file: doveadm_expunge
    job: "/usr/bin/doveadm expunge -A mailbox Trash before 30d"
    name: "Expunge Trash"
    special_time: daily
    user: root

- name: Add cron job to expunge Spam
  ansible.builtin.cron:
    cron_file: doveadm_expunge
    job: "/usr/bin/doveadm expunge -A mailbox Spam before 30d"
    name: "Expunge Spam"
    special_time: daily
    user: root

- name: Copy image extraction script
  ansible.builtin.copy:
    src: usr/local/bin/extract_image_attachments.sh
    dest: /usr/local/bin/extract_image_attachments.sh
    owner: root
    mode: u=rwx,go=rx

- name: Add cron job to extract image attachments
  ansible.builtin.cron:
    cron_file: extract_image_attachments
    job: /usr/local/bin/extract_image_attachments.sh
    name: "Extract image attachments"
    special_time: daily
    user: root
