---
- name: Install APT packages
  become: true
  ansible.builtin.apt:
    state: present
    pkg: "{{ mailinabox_apt_packages }}"

- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: u=rwx,go=rx
  loop:
    - /home/user-data/backup
    - /home/user-data/dns
    - /root/mailinabox/management/

- name: Copy custom DNS settings
  become: true
  ansible.builtin.copy:
    src: home/user-data/dns/custom.yaml
    dest: /home/user-data/dns/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: DNS update

- name: Configure duplicity
  become: true
  block:
    - name: Allow duplicity to be upgraded
      ansible.builtin.dpkg_selections:
        name: duplicity
        selection: install

    - name: Create backup config from template
      ansible.builtin.template:
        src: home/user-data/backup/custom.yaml.j2
        dest: /home/user-data/backup/custom.yaml
        owner: root
        mode: u=rw,go=r
      notify: Perform backup

- name: Configure Munin
  become: true
  block:
    - name: Allow munin-node to read files in home directories
      community.general.ini_file:
        path: /lib/systemd/system/munin-node.service
        section: Service
        option: ProtectHome
        value: read-only
        ignore_spaces: true
        no_extra_spaces: true
        owner: root
        mode: u=rw,go=r
      notify: Reload systemd

    - name: Add duplicity plugin
      ansible.builtin.copy:
        src: etc/munin/plugins/backup_size
        dest: /etc/munin/plugins/backup_size
        owner: root
        mode: u=rwx,go=rx
      notify: Restart munin-node

    - name: Add duplicity plugin configuration
      ansible.builtin.copy:
        src: etc/munin/plugin-conf.d/backup_size
        dest: /etc/munin/plugin-conf.d/backup_size
        owner: root
        mode: u=rw,go=r
      notify: Restart munin-node

    - name: Add munin host configurations
      ansible.builtin.copy:
        src: etc/munin/munin-conf.d/
        dest: /etc/munin/munin-conf.d/
        owner: root
        mode: u=rw,go=r
      notify: Restart munin

    - name: Remove duplicate munin host configuration
      community.general.ini_file:
        path: /etc/munin/munin.conf
        section: box.vangasse.eu
        state: absent
        owner: root
        mode: u=rw,go=r
      notify: Restart munin

- name: Copy files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "/{{ item }}/"
    owner: root
    mode: u=rwX,go=rX
    directory_mode: u=rwx,go=rx
  loop:
    - etc
    - root
