---
- name: Install APT packages
  ansible.builtin.apt:
    state: present
    pkg: "{{ mailinabox_apt_packages }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: u=rwx,go=rx
  loop:
    - /home/user-data/backup
    - /home/user-data/dns

- name: Copy /etc/profile.d files
  ansible.builtin.copy:
    src: etc/profile.d/
    dest: /etc/profile.d/
    owner: root
    mode: u=rwx,go=rx
    directory_mode: u=rwx,go=rx

- name: Copy custom DNS settings
  ansible.builtin.copy:
    src: home/user-data/dns/custom.yaml
    dest: /home/user-data/dns/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: DNS update

- name: Configure duplicity
  ansible.builtin.template:
    src: home/user-data/backup/custom.yaml.j2
    dest: /home/user-data/backup/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: Perform backup

- name: Configure Munin
  ansible.builtin.include_tasks: tasks/munin.yml

- name: Configure UFW to redirect traffic
  ansible.builtin.include_tasks: tasks/configure_ufw_redirection.yml
