---
- name: Copy custom DNS settings
  become: true
  ansible.builtin.copy:
    src: home/user-data/dns/custom.yaml
    dest: /home/user-data/dns/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: DNS update

- name: Install APT packages
  become: true
  ansible.builtin.apt:
    state: present
    pkg: "{{ mailinabox_apt_packages }}"

- name: Install redoc-cli
  become: true
  community.general.npm:
    name: redoc-cli
    global: true

- name: Create backup config from template
  become: true
  ansible.builtin.template:
    src: home/user-data/backup/custom.yaml.j2
    dest: /home/user-data/backup/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: Perform backup

- name: Add webserver to munin configuration
  become: true
  ansible.builtin.copy:
    src: etc/munin/munin-conf.d/webserver
    dest: /etc/munin/munin-conf.d/webserver
    owner: root
    mode: u=rw,go=r
  notify: Restart munin

- name: Expunge Trash and Spam
  become: true
  ansible.builtin.copy:
    src: etc/cron.daily/doveadm-expunge.sh
    dest: /etc/cron.daily/doveadm-expunge.sh
    owner: root
    mode: u=rwx,go=r
