---
- name: Install APT packages
  become: true
  ansible.builtin.apt:
    state: present
    pkg: "{{ mailinabox_apt_packages }}"

- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: u=rwx,go=rx
  loop:
    - /home/user-data/backup
    - /home/user-data/dns

- name: Copy custom DNS settings
  become: true
  ansible.builtin.copy:
    src: home/user-data/dns/custom.yaml
    dest: /home/user-data/dns/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: DNS update

- name: Configure duplicity
  become: true
  ansible.builtin.template:
    src: home/user-data/backup/custom.yaml.j2
    dest: /home/user-data/backup/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: Perform backup

- name: Configure Munin
  ansible.builtin.include_tasks: tasks/munin.yml

- name: Copy /etc files
  become: true
  ansible.builtin.copy:
    src: etc/
    dest: /etc/
    owner: root
    mode: u=rwX,go=rX
    directory_mode: u=rwx,go=rx
