---
- name: Copy custom DNS settings
  become: true
  ansible.builtin.copy:
    src: home/user-data/dns/custom.yaml
    dest: /home/user-data/dns/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: DNS update

- name: Create backup config from template
  become: true
  ansible.builtin.template:
    src: home/user-data/backup/custom.yaml.j2
    dest: /home/user-data/backup/custom.yaml
    owner: root
    mode: u=rw,go=r
  notify: Perform backup
