---
- name: Copy /etc/profile.d files
  ansible.builtin.copy:
    src: etc/profile.d/
    dest: /etc/profile.d/
    owner: root
    mode: u=rwx,go=rx
    directory_mode: u=rwx,go=rx

- name: Configure DNS
  ansible.builtin.include_tasks: tasks/dns.yml

- name: Configure Munin
  ansible.builtin.include_tasks: tasks/munin.yml

- name: Configure UFW to redirect traffic
  ansible.builtin.include_tasks: tasks/configure_ufw_redirection.yml

- name: Configure Backup
  ansible.builtin.include_tasks: tasks/backup.yml
