---
- name: Allow munin-node to read files in home directories
  community.general.ini_file:
    path: /lib/systemd/system/munin-node.service
    section: Service
    option: ProtectHome
    value: false
    ignore_spaces: true
    no_extra_spaces: true
    owner: root
    mode: u=rw,go=r
  notify: Reload systemd

- name: Add munin plugins
  ansible.builtin.copy:
    src: etc/munin/plugins/
    dest: /etc/munin/plugins/
    owner: root
    mode: u=rwx,go=rx
  notify: Restart munin-node

- name: Add munin plugin configurations
  ansible.builtin.copy:
    src: etc/munin/plugin-conf.d/
    dest: /etc/munin/plugin-conf.d/
    owner: root
    mode: u=rw,go=r
  notify: Restart munin-node

- name: Add munin host configurations
  ansible.builtin.copy:
    src: etc/munin/munin-conf.d/
    dest: /etc/munin/munin-conf.d/
    owner: root
    mode: u=rw,go=r
  notify: Restart munin

- name: Remove duplicate munin host configuration
  community.general.ini_file:
    path: /etc/munin/munin.conf
    section: box.vangasse.eu
    state: absent
    owner: root
    mode: u=rw,go=r
  notify: Restart munin
