#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
backup_size.label Total size of backups
graph_args --base 1024 -l 0
graph_category backup
graph_info The total size of duplicity backups.
graph_title Backup size
graph_vlabel Backup size
EOM
        exit 0;;
esac

printf "backup_size.value "
/root/mailinabox/management/backup.py --list | cut --fields=2 | awk '{s+=$1} END {printf "%.0f\n", s}'
