---
name: ansible-lint
on:
  workflow_call:
  workflow_dispatch:
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ansible-lint
        id: ansible-lint
        uses: ansible/ansible-lint@main
