---
name: 🚀 Ansible Run

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      check-mode:
        description: 'Run in dry-run mode (ansible --check)'
        required: false
        default: false
        type: boolean
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      VAULT_PASSWORD:
        required: true
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible-playbook:
    name: Ansible Playbook
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - amedee.be
          - box.vangasse.eu
    concurrency:
      group: ${{ format(
        'ansible-run-{0}{1}-{2}-{3}',
        inputs.check-mode && 'check-' || '',
        matrix.host,
        github.workflow,
        github.ref) }}
      cancel-in-progress: true
    env:
      ANSIBLE_CONFIG: ansible.cfg
      ANSIBLE_STDOUT_CALLBACK: yaml
    steps:
      - name: Collect Workflow Telemetry
        # yamllint disable-line rule:line-length
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Ansible roles and collections cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .ansible/
            roles/
          key: ansible-deps-${{ hashFiles('requirements.yml') }}
          fail-on-cache-miss: true

      - name: Copy Ansible collections to proper directory
        run: |
          mkdir -p .ansible/collections /home/runner/.ansible
          cp -r .ansible/collections /home/runner/.ansible/

      - name: Create controlmasters directory
        run: mkdir --parents ~/.ssh/controlmasters

      - name: Deploy changes to servers
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@93764e7048f4dd16117d134dadb4b36e8ee73227 # v4
        with:
          playbook: playbooks/site.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory/production
            --limit ${{ matrix.host }}
            ${{ inputs.check-mode && '--check' || '' }}
            -vv

      - name: Archive Ansible log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format(
            'ansible-{0}{1}.log',
            inputs.check-mode && 'check-' || '',
            matrix.host) }}
          path: ~/.ansible/ansible.log
          compression-level: 9
          overwrite: true

      - name: checkrun-timechart
        # yamllint disable-line rule:line-length
        uses: urcomputeringpal/checkrun-timechart-action@9de4251d7983342ccf09b84ed921326887571853 # v0.0.8
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          SUMMARY: "true"
