---
name: ansible-deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ansible-lint]
    types:
      - completed
jobs:
  ansible-playbook:
    name: Ansible Playbook
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set ansible.cfg location
        run: echo "ANSIBLE_CONFIG=ansible.cfg" >> $GITHUB_ENV
      - name: Install community.general
        run: ansible-galaxy collection install community.general
      - name: Create controlmasters directory
        run: mkdir --parents ~/.ssh/controlmasters
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/site.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory inventory/production
