---
name: Deploy to Production

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  codacy:
    name: Codacy Security Scan
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: amedee/ansible-servers/.github/workflows/codacy.yml@main

  ansible-lint:
    name: Ansible Lint
    uses: amedee/ansible-servers/.github/workflows/ansible-lint.yml@main

  shellcheck:
    name: ShellCheck
    permissions:
      contents: read
    uses: amedee/ansible-servers/.github/workflows/shellcheck.yml@main

  ansible-playbook:
    name: Ansible Playbook
    runs-on: ubuntu-latest
    needs: [codacy, ansible-lint, shellcheck]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
            echo "ANSIBLE_CONFIG=ansible.cfg" >> $GITHUB_ENV
            echo "ANSIBLE_STDOUT_CALLBACK=yaml" >> $GITHUB_ENV

      - name: Install community.general
        run: ansible-galaxy collection install community.general

      - name: Create controlmasters directory
        run: mkdir --parents ~/.ssh/controlmasters

      - name: Deploy changes to servers
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/site.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory/production
