---
name: Ansible Lint

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install community.general
        run: ansible-galaxy collection install --force community.general

      - name: Install community.mysql
        run: ansible-galaxy collection install --force community.mysql

      - name: Run ansible-lint
        id: ansible-lint
        uses: ansible/ansible-lint@main
