---
name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5 * * *'

permissions:
  contents: read

jobs:
  codacy:
    name: Codacy Security Scan
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: amedee/ansible-servers/.github/workflows/codacy.yml@main

  ansible-lint:
    name: Ansible Lint
    uses: amedee/ansible-servers/.github/workflows/ansible-lint.yml@main

  ansible-playbook:
    name: Ansible Playbook
    runs-on: ubuntu-latest
    needs: [codacy, ansible-lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set ansible.cfg location
        run: echo "ANSIBLE_CONFIG=ansible.cfg" >> $GITHUB_ENV

      - name: Install community.general
        run: ansible-galaxy collection install community.general

      - name: Create controlmasters directory
        run: mkdir --parents ~/.ssh/controlmasters

      - name: Deploy changes to servers
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/site.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory inventory/production
            -vvv
