---
name: Ansible Lint

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible Galaxy collections
        run: ansible-galaxy collection install --force community.general community.mysql amazon.aws

      - name: Run ansible-lint
        id: ansible-lint
        uses: ansible/ansible-lint@b4018c22f8fe8371bd6845d0cd62cebea54ce012 # v24
