---
name: Ansible Lint

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '**.cfg'
      - '**.j2'
      - '**.yml'
      - '!.github/**'
      - '.github/workflows/ansible-lint.yml'
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ansible-lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible Galaxy collections
        run: ansible-galaxy install -r requirements.yml

      - name: Run ansible-lint
        id: ansible-lint
        # yamllint disable-line rule:line-length
        uses: ansible/ansible-lint@9cf49a01ac6b34f45aab16f0bbac1196fcd681e5  # v24
