---
name: 🚀 Deploy to Production

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      host:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      VAULT_PASSWORD:
        required: true
  workflow_dispatch:
    inputs:
      host:
        description: 'Target host (e.g. box.vangasse.eu)'
        required: true
        type: string

concurrency:
  group: deploy-production-${{ inputs.host }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible-playbook:
    name: Ansible Playbook
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CONFIG: ansible.cfg
      ANSIBLE_STDOUT_CALLBACK: yaml
    steps:
      - name: Collect Workflow Telemetry
        # yamllint disable-line rule:line-length
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible Galaxy collections
        run: ansible-galaxy install -r requirements.yml

      - name: Create controlmasters directory
        run: mkdir --parents ~/.ssh/controlmasters

      - name: Deploy changes to servers
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@a4133a9690f77b38c8227021ed497fc1267635d5 # v3
        with:
          playbook: playbooks/site.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory/production
            --limit ${{ inputs.host }}
            -vvv

      - name: Archive Ansible log
        uses: actions/upload-artifact@v4
        with:
          name: ansible-${{ inputs.host }}.log
          path: ~/.ansible/ansible.log
          compression-level: 9
          overwrite: true

      - name: checkrun-timechart
        # yamllint disable-line rule:line-length
        uses: urcomputeringpal/checkrun-timechart-action@9de4251d7983342ccf09b84ed921326887571853 # v0.0.8
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          SUMMARY: "true"
