---
name: 🔍 Dry Run on Production

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      host:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      VAULT_PASSWORD:
        required: true
  workflow_dispatch:
    inputs:
      host:
        description: 'Target host (e.g. box.vangasse.eu)'
        required: true
        type: string

concurrency:
  group: dry-run-production-${{ inputs.host }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  ansible-check:
    name: Ansible Dry Run
    runs-on: ubuntu-latest
    env:
      ANSIBLE_CONFIG: ansible.cfg
      ANSIBLE_STDOUT_CALLBACK: yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-install Ansible Galaxy roles (with retry)
        run: |
          for i in {1..5}; do
            if ansible-galaxy install -r requirements.yml; then
              break
            else
              sleep $((i * 10))
            fi
          done

      - name: Create controlmasters directory
        run: mkdir --parents ~/.ssh/controlmasters

      - name: Dry-run playbook on production host
        # yamllint disable-line rule:line-length
        uses: dawidd6/action-ansible-playbook@a4133a9690f77b38c8227021ed497fc1267635d5 # v3
        with:
          playbook: playbooks/site.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          options: |
            --inventory inventory/production
            --limit ${{ inputs.host }}
            --check
            -vvv

      - name: Archive Ansible dry-run log
        uses: actions/upload-artifact@v4
        with:
          name: dry-run-${{ inputs.host }}.log
          path: ~/.ansible/ansible.log
          compression-level: 9
          overwrite: true
