---
name: 🧪🧼🚀 Wash, Test, Deploy

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - "**"
      - "!*.md"
      - "!.github/workflows/gource.yml"
      - "!.pre-commit-config.yaml"
      - "!Vagrantfile"
      - "!deploy_to_staging.sh"
      - "!resize_disk.sh"
  schedule:
    - cron: "10 3 * * SAT"
  workflow_dispatch:

concurrency:
  group: pipeline-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ansible-cache:
    name: 🚀 Ansible Cache
    uses: ./.github/workflows/ansible-cache.yml

  super-linter:
    name: 🛠️ Code Quality — Super-Linter
    permissions:
      contents: read
      packages: read
      pull-requests: read
      statuses: write
    uses: ./.github/workflows/code-quality-super-linter.yml
    secrets:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      ANSIBLE_DEP_UPDATER_TOKEN: ${{ secrets.ANSIBLE_DEP_UPDATER_TOKEN }}
    needs:
      - ansible-cache

  ansible-lint:
    name: 🛠️ Code Quality — Ansible Lint
    uses: ./.github/workflows/code-quality-ansible-lint.yml
    needs:
      - ansible-cache

  eslint:
    name: 🛠️ Code Quality — ESLint
    uses: ./.github/workflows/code-quality-eslint.yml

  pylint:
    name: 🛠️ Code Quality — Pylint
    uses: ./.github/workflows/code-quality-pylint.yml

  validate-configs:
    name: 🛠️ Code Quality — Validate Configs
    uses: ./.github/workflows/code-quality-validate-configs.yml

  pre-commit:
    name: 🛠️ Code Quality — Pre-Commit
    uses: ./.github/workflows/code-quality-pre-commit.yml

  dry-run:
    name: 🔍 Dry Run on Production
    uses: ./.github/workflows/ansible-run.yml
    needs:
      - ansible-cache
    with:
      check-mode: true
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}

  deploy:
    name: 🚀 Deploy to Production
    uses: ./.github/workflows/ansible-run.yml
    needs:
      - ansible-cache
      - dry-run
      - super-linter
      - ansible-lint
      - eslint
      - pylint
      - validate-configs
      - pre-commit
    with:
      check-mode: false
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
