---
name: ShellCheck

on:  # yamllint disable-line rule:truthy
  push:
    paths:
      - '**'
      - '!**.cfg'
      - '!**.md'
      - '!**.yml'
      - '.github/workflows/shellcheck.yml'
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        # yamllint disable-line rule:line-length
        uses: azohra/shell-linter@6bbeaa868df09c34ddc008e6030cfe89c03394a1  # v0.6.0
        with:
          # yamllint disable-line rule:line-length
          exclude-paths: "Vagrantfile,LICENSE,.github/CODEOWNERS,roles/*/files/etc/munin/*-conf.d"
