---
name: Super-linter

on: # yamllint disable-line rule:truthy
  push:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: read
  # To report GitHub Actions status checks
  statuses: write

jobs:
  lint:
    name: Super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Run Super-linter
        # yamllint disable-line rule:line-length
        uses: super-linter/super-linter/slim@4e8a7c2bf106c4c766c816b35ec612638dc9b6b2 # v7.3.0
        env:
          ANSIBLE_DIRECTORY: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_GIT_COMMITLINT: false
          FIX_YAML_PRETTIER: true

      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@f65a78c343ee50737aebbe653e35f3067752c7b3 # v2.8.0
        name: git-diff-action
        id: git-diff-action
        with:
          base_branch: origin/${{ github.head_ref || github.ref_name }}
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: true

      # Print the diff in JSON format
      - name: print json diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.json-diff-path }}
        run: cat "$DIFF"

      # Print the diff in raw git format
      - name: print raw diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
        run: cat "$DIFF"
