---
name: GitHub Workflows Metrics

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 10 * * SAT"
  workflow_dispatch:

permissions:
  actions: read
  issues: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: yykamei/github-workflows-metrics@0fdd40d602a75c5228c830fa33a02e80fcbb689b # v0.3.8
        with:
          only: ansible-deploy.yml
          status: success
