---
name: GitHub Workflows Metrics

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 10 * * SAT"
  workflow_dispatch:

permissions:
  actions: read
  issues: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: yykamei/github-workflows-metrics@88ef4f78069ed673198c4da371b099d24bffabca # v0.3.7
        with:
          only: ansible-deploy.yml
          status: success
