---
name: GitHub Workflows Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 * * SAT"

permissions:
  actions: read
  issues: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/github-workflows-metrics@369e7ccc2b7fa9bc27f79e7e0c36fb95db25379e # v0.3.6
        with:
          only: ansible-deploy.yml
          status: success
