---
- name: Create WordPress database
  ansible.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create WordPress database user
  ansible.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    host: "{{ wp_db_host }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    column_case_sensitive: true
    state: present
    login_user: root
    login_unix_socket: /run/mysqld/mysqld.sock
  no_log: true
