---
- name: Create WordPress MySQL database and user
  ansible.builtin.import_tasks: wordpress_db.yml

- name: "Install WordPress in {{ webserver_directory }}"
  ansible.builtin.import_tasks: wordpress.yml
