---
- name: Install WordPress packages
  ansible.builtin.apt:
    name: "{{ wp_packages + wp_php_packages + wp_python_packages }}"
    state: present

- name: Configure WordPress database
  ansible.builtin.import_tasks:
    file: database_init.yml

- name: "Install WordPress in {{ wp_webserver_directory }}"
  ansible.builtin.import_tasks:
    file: wordpress.yml

- name: Manage WordPress plugins
  ansible.builtin.import_tasks:
    file: wordpress_plugins.yml

- name: Configure Redis for WordPress
  ansible.builtin.import_tasks:
    file: wordpress_redis.yml

- name: Manage WordPress themes
  ansible.builtin.import_tasks:
    file: wordpress_themes.yml
