---
- name: Enable WP Redis
  become: true
  become_user: "{{ wp_webserver_user }}"
  ansible.builtin.command:
    argv: "{{ wp_cli + ['redis', 'enable'] }}"
  register: wp_redis_enable
  changed_when: "'Object cache enabled' in wp_redis_enable.stdout"
