---
- name: Check WordPress theme {{ wp_theme }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - is-installed
      - "{{ wp_theme }}"
      - "--path={{ webserver_directory }}"
  changed_when: false
  failed_when: false
  register: wp_theme_is_installed

- name: Uninstall WordPress theme {{ wp_theme }}
  when: wp_theme_is_installed.rc | int == 0
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - theme
      - uninstall
      - "{{ wp_theme }}"
      - "--path={{ webserver_directory }}"
  changed_when: true
