---
- name: Check WordPress plugin {{ wp_plugin }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - is-installed
      - "{{ wp_plugin }}"
      - "--path={{ webserver_directory }}"
  changed_when: false
  failed_when: false
  register: wp_plugin_is_installed

- name: Install WordPress plugin {{ wp_plugin }}
  when: wp_plugin_is_installed.rc | int != 0
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - install
      - "{{ wp_plugin }}"
      - --activate
      - "--path={{ webserver_directory }}"
  changed_when: true

- name: Check if auto-updates are disabled for {{ wp_plugin }}
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - auto-updates
      - status
      - "{{ wp_plugin }}"
      - "--path={{ webserver_directory }}"
      - "--disabled-only"
      - "--field=name"
  changed_when: false
  register: wp_plugin_auto_updates

- name: Enable auto-updates if disabled for {{ wp_plugin }}
  when: wp_plugin_auto_updates.stdout | trim == wp_plugin
  become: true
  become_user: "{{ webserver_user }}"
  ansible.builtin.command:
    argv:
      - wp
      - plugin
      - auto-updates
      - enable
      - "{{ wp_plugin }}"
      - "--path={{ webserver_directory }}"
  changed_when: true
