---
name: Extract Staged Git Diff

description: Extract git diff for staged files matching given globs

inputs:
  globs:
    description: 'Glob patterns to diff (space separated)'
    default: '.'

outputs:
  has_diff:
    description: 'true if diff found, false otherwise'
    value: ${{ steps.diff_check.outputs.has_diff }}
  diff_content:
    description: 'Git diff output'
    value: ${{ steps.diff_check.outputs.diff_content }}

runs:
  using: "composite"
  steps:
    - id: diff_check
      run: |
        # Add files matching add-globs
        for pattern in ${{ inputs.globs }}; do
          git add $pattern || true
        done

        # Get diff for diff-globs
        diff_output=$(git diff --cached --unified=0 -- ${{ inputs.globs }})

        if [[ -n "$diff_output" ]]; then
          {
            echo "has_diff=true"
            echo "diff_content<<EOF"
            echo "$diff_output"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        else
          echo "has_diff=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
